development:
  adapter: postgresql
  database: hambarrier_development
  encoding: utf8
  username: 
  password:
  host: localhost

production:
  adapter: postgresql
  database: hambarrier_production
  encoding: utf8
  username: 
  password:
  host: localhost

test:
  adapter: postgresql
  database: hambarrier_test
  encoding: utf8
  username: 
  password:
  host: localhost